"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 15:13:50.265904
"""
from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.config import get_settings

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIM = get_settings().embedding_dim

APPEND_ONLY_SQL = [
    """CREATE OR REPLACE FUNCTION audit_events_append_only() RETURNS trigger AS $$
    BEGIN
        RAISE EXCEPTION 'audit_events is append-only (% blocked)', TG_OP
            USING ERRCODE = 'insufficient_privilege';
    END;
    $$ LANGUAGE plpgsql""",
    """CREATE TRIGGER audit_events_no_update BEFORE UPDATE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION audit_events_append_only()""",
    """CREATE TRIGGER audit_events_no_delete BEFORE DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION audit_events_append_only()""",
    """CREATE TRIGGER audit_events_no_truncate BEFORE TRUNCATE ON audit_events
        FOR EACH STATEMENT EXECUTE FUNCTION audit_events_append_only()""",
    "REVOKE UPDATE, DELETE, TRUNCATE ON audit_events FROM PUBLIC",
]


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_events_hash')),
    sa.UniqueConstraint('seq', name=op.f('uq_audit_events_seq'))
    )
    op.create_table('branches',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('code', name=op.f('uq_branches_code'))
    )
    op.create_table('departments',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code'))
    )
    op.create_table('contacts',
    sa.Column('role_label', sa.String(length=200), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('phone_ext', sa.String(length=40), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('pager', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('escalation_for', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_contacts_branch_id_branches')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_contacts_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('clinician', 'author', 'approver', 'admin', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_users_branch_id_branches')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('documents',
    sa.Column('doc_code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('doc_type', sa.Enum('protocol', 'drug_guideline', 'circular', 'sop', 'external_reference', name='doc_type', native_enum=False, length=30), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('applies_to_all_branches', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_documents_department_id_departments')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_documents_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('doc_code', name=op.f('uq_documents_doc_code'))
    )
    op.create_table('query_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('redacted_question', sa.Text(), nullable=False),
    sa.Column('pii_redacted', sa.Boolean(), nullable=False),
    sa.Column('route', sa.Enum('answer', 'clarify', 'out_of_scope', 'high_risk', name='route', native_enum=False, length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=True),
    sa.Column('prompt_version', sa.String(length=120), nullable=True),
    sa.Column('retrieval', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_query_logs_branch_id_branches')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_query_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_query_logs'))
    )
    op.create_table('answer_logs',
    sa.Column('query_id', sa.Uuid(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('answered', 'abstained', 'partial', name='outcome', native_enum=False, length=20), nullable=False),
    sa.Column('abstain_reason', sa.String(length=40), nullable=True),
    sa.Column('generation_mode', sa.String(length=20), nullable=True),
    sa.Column('verifier_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quick_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['query_logs.id'], name=op.f('fk_answer_logs_query_id_query_logs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_logs')),
    sa.UniqueConstraint('query_id', name=op.f('uq_answer_logs_query_id'))
    )
    op.create_table('document_branches',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_document_branches_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_branches_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'branch_id', name=op.f('pk_document_branches'))
    )
    op.create_table('document_versions',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'superseded', 'retired', name='version_status', native_enum=False, length=20), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('review_due', sa.Date(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('ingest_status', sa.Enum('pending', 'processing', 'ready', 'failed', name='ingest_status', native_enum=False, length=20), nullable=False),
    sa.Column('ingest_error', sa.Text(), nullable=True),
    sa.Column('parser', sa.String(length=40), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('ocr_min_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_page_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ocr_acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('ocr_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parse_warnings', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_document_versions_approved_by_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ocr_acknowledged_by'], ['users.id'], name=op.f('fk_document_versions_ocr_acknowledged_by_users')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_document_versions_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version_label', name='uq_document_versions_doc_label'),
    sa.UniqueConstraint('file_sha256', name=op.f('uq_document_versions_file_sha256'))
    )
    op.create_index('ix_document_versions_status_effective', 'document_versions', ['status', 'effective_from'], unique=False)
    op.create_table('chunks',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('section_path', sa.String(length=80), nullable=False),
    sa.Column('covered_paths', postgresql.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('context_header', sa.String(length=600), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_table', sa.Boolean(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english'::regconfig, coalesce(context_header, '') || ' ' || coalesce(text, ''))", persisted=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(EMBEDDING_DIM), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], name=op.f('fk_chunks_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    op.create_index('ix_chunks_embedding_hnsw', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chunks_tsv', 'chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_version_ordinal', 'chunks', ['version_id', 'ordinal'], unique=False)
    op.create_table('feedback',
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('wrong', 'outdated', 'unhelpful', 'helpful', name='feedback_kind', native_enum=False, length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('routed_to_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', name='feedback_status', native_enum=False, length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer_logs.id'], name=op.f('fk_feedback_answer_id_answer_logs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routed_to_user_id'], ['users.id'], name=op.f('fk_feedback_routed_to_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedback_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.create_table('supersessions',
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('target_document_id', sa.Uuid(), nullable=False),
    sa.Column('target_section_path', sa.String(length=80), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('suggested', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_supersessions_confirmed_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_supersessions_created_by_users')),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], name=op.f('fk_supersessions_source_version_id_document_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], name=op.f('fk_supersessions_target_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supersessions'))
    )
    op.create_table('citations',
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('marker', sa.String(length=10), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=True),
    sa.Column('supported', sa.Boolean(), nullable=False),
    sa.Column('support_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer_logs.id'], name=op.f('fk_citations_answer_id_answer_logs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_citations_chunk_id_chunks')),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], name=op.f('fk_citations_version_id_document_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations'))
    )
    op.create_table('conflicts',
    sa.Column('chunk_a_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_b_id', sa.Uuid(), nullable=False),
    sa.Column('detected_by', sa.Enum('ingest', 'query', 'user', name='detected_by', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', 'dismissed', name='conflict_status', native_enum=False, length=20), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_a_id'], ['chunks.id'], name=op.f('fk_conflicts_chunk_a_id_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_b_id'], ['chunks.id'], name=op.f('fk_conflicts_chunk_b_id_chunks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_conflicts_owner_user_id_users')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_conflicts_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conflicts')),
    sa.UniqueConstraint('chunk_a_id', 'chunk_b_id', name='uq_conflicts_pair')
    )
    # ### end Alembic commands ###

    # Database-level guards for the values the safety logic depends on.
    op.create_check_constraint(
        'status_valid', 'document_versions', "status IN ('draft', 'approved', 'superseded', 'retired')")
    op.create_check_constraint(
        'approved_has_approver', 'document_versions', "status <> 'approved' OR approved_at IS NOT NULL")
    op.create_check_constraint('role_valid', 'users', "role IN ('clinician', 'author', 'approver', 'admin')")
    op.create_check_constraint(
        'doc_type_valid', 'documents',
        "doc_type IN ('protocol', 'drug_guideline', 'circular', 'sop', 'external_reference')")
    op.create_check_constraint('distinct_chunks', 'conflicts', 'chunk_a_id <> chunk_b_id')
    for statement in APPEND_ONLY_SQL:
        op.execute(statement)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_update ON audit_events")
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_delete ON audit_events")
    op.execute("DROP TRIGGER IF EXISTS audit_events_no_truncate ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS audit_events_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conflicts')
    op.drop_table('citations')
    op.drop_table('supersessions')
    op.drop_table('feedback')
    op.drop_index('ix_chunks_version_ordinal', table_name='chunks')
    op.drop_index('ix_chunks_tsv', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_embedding_hnsw', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('chunks')
    op.drop_index('ix_document_versions_status_effective', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('document_branches')
    op.drop_table('answer_logs')
    op.drop_table('query_logs')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('contacts')
    op.drop_table('departments')
    op.drop_table('branches')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
